# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc6', '0002_appsettings_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'Application Setting'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting'},
        ),
        migrations.AddField(
            model_name='payments',
            name='disbid',
            field=models.CharField(blank=True, db_column='DisbID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='enrollid',
            field=models.CharField(blank=True, db_column='EnrollID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='exported',
            field=models.IntegerField(blank=True, db_column='exported', default=0, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='exported_at',
            field=models.DateTimeField(blank=True, db_column='exported_at', null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='postdate',
            field=models.DateTimeField(blank=True, db_column='PostDate', null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='school_id',
            field=models.IntegerField(blank=True, db_column='School_ID', null=True),
        ),
        migrations.AddField(
            model_name='studentfunding',
            name='awardid',
            field=models.CharField(blank=True, db_column='AwardID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfunding',
            name='disbid',
            field=models.CharField(blank=True, db_column='DisbID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfunding',
            name='disbnum',
            field=models.CharField(blank=True, db_column='DisbNum', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfunding',
            name='enrollid',
            field=models.CharField(blank=True, db_column='EnrollID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfunding',
            name='scheddate',
            field=models.DateTimeField(blank=True, db_column='SchedDate', null=True),
        ),
    ]
